---
sudo: required

env:
  - distribution: centos
    version: 7
  - distribution: fedora
    version: 26
  - distribution: ubuntu
    version: xenial
  - distribution: debian
    version: stretch

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/gmambro.zookeeper:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/gmambro.zookeeper/test.yml --syntax-check'
  
# prereqs
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/gmambro.zookeeper/tests/prereqs.yml'
  - 'sudo docker exec --tty "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-galaxy install geerlingguy.java'
  
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/gmambro.zookeeper/tests.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/gmambro.zookeeper/tests/test.yml
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

# notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
