---

- set_fact:
    zookeeper_node_id: "{{ zookeeper_ensemble[inventory_hosname]['id'] }}"
  when: |
    zookeeper_ensemble is mapping and
      inventory_hostname in zookeeper_ensemble

- set_fact:
    zookeeper_node_id: "{{item.0|int + 1 }}"
  with_indexed_items: "{{ zookeeper_ensemble }}"
  when: |
    zookeeper_ensemble is not mapping and
    inventory_hostname == item.1


- debug: var=zookeeper_node_id

- name: Check variables
  assert:
    that:
      - '{{item}} is defined'
      - '{{item}} != ""'
  with_items:
      - zookeeper_node_id

- name: Check list variables
  assert:
    that:
      - '{{item}} is defined'
      - '{{item}} | count > 0'
    msg: "{{ item }} should be defined with at least one item"
  with_items:
      - zookeeper_ensemble
