---
- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

- name: restart zookeeper
  service: 
    name: zookeeper
    state: restarted
  when:  zookeeper_manage_service 
